"""
pptx_generator.py — Generates a professional 10-slide PowerPoint report.
"""

import io
from datetime import datetime
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.chart.data import ChartData
from pptx.enum.chart import XL_CHART_TYPE


# ── Brand colors ──────────────────────────────────────────────────────────────
C_BG       = RGBColor(255, 249, 196)      # Light Yellow
C_CARD     = RGBColor(255, 255, 255)      # White
C_PRIMARY  = RGBColor(93, 64, 55)         # Brown
C_ACCENT   = RGBColor(255, 152, 0)        # Orange
C_WHITE    = RGBColor(255, 255, 255)
C_LIGHT    = RGBColor(121, 85, 72)        # Light Brown
C_GOLD     = RGBColor(255, 193, 7)
C_RED      = RGBColor(211, 47, 47)
C_TEXT     = RGBColor(93, 64, 55)         # Brown Text


def _rgb(color: RGBColor):
    return color


def _add_slide(prs, layout_idx=6):
    layout = prs.slide_layouts[layout_idx]
    return prs.slides.add_slide(layout)


def _fill_bg(slide, color: RGBColor):
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = color


def _textbox(slide, text, left, top, width, height,
             font_size=18, bold=False, color=None, align=PP_ALIGN.LEFT,
             font_name="Inter"):
    txb = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height))
    tf = txb.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.alignment = align
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    run.font.name = font_name
    run.font.color.rgb = color or C_TEXT
    return txb


def _rect(slide, left, top, width, height, fill_color, alpha=None):
    shape = slide.shapes.add_shape(
        1,  # MSO_SHAPE_TYPE.RECTANGLE
        Inches(left), Inches(top), Inches(width), Inches(height))
    shape.fill.solid()
    shape.fill.fore_color.rgb = fill_color
    shape.line.fill.background()
    return shape


def _divider(slide, top, color=C_PRIMARY):
    _rect(slide, 0.5, top, 9.0, 0.04, color)


def _stat_box(slide, label, value, left, top, w=2.1, h=1.2):
    _rect(slide, left, top, w, h, C_CARD)
    _textbox(slide, value, left + 0.1, top + 0.1, w - 0.2, 0.55,
             font_size=20, bold=True, color=C_ACCENT, align=PP_ALIGN.CENTER)
    _textbox(slide, label, left + 0.1, top + 0.65, w - 0.2, 0.45,
             font_size=10, color=C_LIGHT, align=PP_ALIGN.CENTER)


def _fmt(n):
    if n >= 1_000_000:
        return f"{n/1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n/1_000:.1f}K"
    return str(n)


# ══════════════════════════════════════════════════════════════════════════════
# SLIDE BUILDERS
# ══════════════════════════════════════════════════════════════════════════════

def slide_cover(prs, own, competitors, report_date):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 2.8, C_PRIMARY)
    _textbox(sl, "VIDEO COMPETITOR INTELLIGENCE", 0.4, 0.5, 9.2, 0.8,
             font_size=28, bold=True, color=C_WHITE, align=PP_ALIGN.CENTER)
    _textbox(sl, "EXECUTIVE ANALYSIS REPORT", 0.4, 1.2, 9.2, 0.6,
             font_size=20, color=C_GOLD, align=PP_ALIGN.CENTER)
    
    _textbox(sl, f"Your Company: {own}", 0.5, 3.3, 9, 0.5,
             font_size=16, bold=True, color=C_PRIMARY)
    comp_str = " | ".join(competitors)
    _textbox(sl, f"Competitors Analysed: {comp_str}", 0.5, 3.8, 9, 0.4,
             font_size=13, color=C_LIGHT)
             
    _divider(sl, 4.4, C_PRIMARY)
    
    _textbox(sl, f"Report Date: {report_date}    |    Generated by P2P Platform",
             0.5, 4.6, 9, 0.4, font_size=11, color=C_LIGHT)
    _textbox(sl, "CONFIDENTIAL / INTERNAL USE ONLY", 0.5, 5.2, 9, 0.35,
             font_size=10, bold=True, color=C_RED, align=PP_ALIGN.CENTER)


def slide_executive_summary(prs, own, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_PRIMARY)
    _textbox(sl, "EXECUTIVE SUMMARY", 0.4, 0.15, 9.2, 0.6,
             font_size=24, bold=True, color=C_WHITE)

    # Calculate some strategy stats
    leader = max(all_data.items(), key=lambda x: x[1].get("channel", {}).get("subscribers", 0), default=(own, {}))
    leader_name = leader[0]
    
    best_eng = max(all_data.items(), key=lambda x: x[1].get("analytics", {}).get("avg_engagement_rate", 0), default=(own, {}))
    best_eng_name = best_eng[0]

    summary_lines = [
        f"▶  Market Leader: {leader_name} currently commands the largest audience share.",
        f"▶  Engagement Winner: {best_eng_name} has the highest viewer interaction rate, showing stronger community loyalty.",
        f"▶  Strategic Focus for {own}: The data reveals significant gaps in publishing cadence and short-form video adaptation.",
        "▶  This report breaks down channel authority, content themes, and specific viewer engagement metrics.",
        "▶  Actionable marketing recommendations are detailed on slides 8-9 for immediate implementation.",
    ]
    top = 1.3
    for line in summary_lines:
        _textbox(sl, line, 0.5, top, 9.0, 0.42, font_size=13, color=C_PRIMARY)
        top += 0.55

    # Leader callout box
    subs = leader[1].get("channel", {}).get("subscribers", 0)
    _rect(sl, 0.5, top + 0.3, 9.0, 1.0, C_CARD)
    _textbox(sl, f"🏆  Dominant Channel: {leader_name}  |  {_fmt(subs)} Subscribers",
             0.7, top + 0.5, 8.6, 0.5, font_size=15, bold=True, color=C_PRIMARY)


def slide_channel_overview(prs, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "CHANNEL OVERVIEW COMPARISON", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)
    
    _textbox(sl, "A high-level view of audience size and total video output. A high video count with low subscribers indicates poor content-market fit.", 0.4, 1.0, 9.2, 0.4, font_size=11, color=C_LIGHT)

    headers = ["Company", "Subscribers", "Total Videos", "Total Views", "Country"]
    col_w = [2.2, 1.7, 1.6, 1.9, 1.4]
    col_x = [0.3]
    for w in col_w[:-1]:
        col_x.append(col_x[-1] + w)

    top = 1.6
    for i, h in enumerate(headers):
        _textbox(sl, h, col_x[i], top, col_w[i], 0.35,
                 font_size=12, bold=True, color=C_PRIMARY)
    _divider(sl, 2.0, C_PRIMARY)

    top = 2.2
    for company, data in all_data.items():
        ch = data.get("channel", {})
        row = [
            company[:22],
            _fmt(ch.get("subscribers", 0)),
            _fmt(ch.get("total_videos", 0)),
            _fmt(ch.get("total_views", 0)),
            ch.get("country", "N/A"),
        ]
        bg = C_CARD if list(all_data.keys()).index(company) % 2 == 0 else C_BG
        _rect(sl, 0.3, top, 9.4, 0.45, bg)
        for i, val in enumerate(row):
            _textbox(sl, val, col_x[i], top + 0.08, col_w[i], 0.3,
                     font_size=11, color=C_PRIMARY)
        top += 0.5


def slide_subscribers_chart(prs, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "SUBSCRIBER COUNT — BRAND REACH", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)

    cd = ChartData()
    cd.categories = list(all_data.keys())
    cd.add_series("Subscribers",
                  [d.get("channel", {}).get("subscribers", 0) for d in all_data.values()])

    chart = sl.shapes.add_chart(
        XL_CHART_TYPE.COLUMN_CLUSTERED,
        Inches(0.5), Inches(1.2), Inches(9.0), Inches(5.5), cd
    ).chart

    chart.has_legend = False
    chart.has_title = False
    
    # Color each individual bar point with a theme color
    if len(chart.series) > 0:
        series = chart.series[0]
        colors = [C_PRIMARY, C_ACCENT, C_GOLD, C_LIGHT, RGBColor(210, 180, 140)]
        for j, point in enumerate(series.points):
            fill = point.format.fill
            fill.solid()
            fill.fore_color.rgb = colors[j % len(colors)]


def slide_top_videos(prs, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "TOP PERFORMING VIDEOS BY VIEWS", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)

    top = 1.3
    for company, data in all_data.items():
        analytics = data.get("analytics", {})
        top_vids = analytics.get("top_videos", [])[:2]
        _textbox(sl, f"► {company}", 0.4, top, 9.0, 0.3,
                 font_size=14, bold=True, color=C_PRIMARY)
        top += 0.38
        if not top_vids:
            _textbox(sl, "  No video data available.", 0.6, top, 8.8, 0.28,
                     font_size=11, color=C_LIGHT)
            top += 0.4
        else:
            for v in top_vids:
                title = v.get("title", "")[:60]
                views = _fmt(v.get("views", 0))
                likes = _fmt(v.get("likes", 0))
                txt = f"  📹 {title}  |  👁 {views} views  |  👍 {likes} likes"
                _textbox(sl, txt, 0.6, top, 9.0, 0.28, font_size=11, color=C_LIGHT)
                top += 0.35
        if top > 6.8:
            break


def slide_content_themes(prs, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "CONTENT TOPICS & THEMES", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)

    top = 1.3
    for company, data in all_data.items():
        themes = data.get("analytics", {}).get("content_themes", [])
        _textbox(sl, f"► {company}", 0.4, top, 9.0, 0.3,
                 font_size=14, bold=True, color=C_PRIMARY)
        top += 0.38
        theme_str = "  " + "   |   ".join(themes[:8]) if themes else "  No theme data"
        _textbox(sl, theme_str, 0.6, top, 9.0, 0.28, font_size=11, color=C_ACCENT)
        top += 0.45
        if top > 6.5:
            break


def slide_posting_frequency(prs, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "POSTING FREQUENCY & CONSISTENCY", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)

    cd = ChartData()
    cd.categories = list(all_data.keys())
    cd.add_series("Posts/Month",
                  [d.get("analytics", {}).get("posting_frequency_per_month", 0)
                   for d in all_data.values()])

    chart = sl.shapes.add_chart(
        XL_CHART_TYPE.BAR_CLUSTERED,
        Inches(0.5), Inches(1.2), Inches(9.0), Inches(4.5), cd
    ).chart
    chart.has_legend = False
    chart.has_title = False
    
    # Color each individual horizontal bar point with a theme color
    if len(chart.series) > 0:
        series = chart.series[0]
        colors = [C_ACCENT, C_PRIMARY, C_GOLD, C_LIGHT, RGBColor(210, 180, 140)]
        for j, point in enumerate(series.points):
            fill = point.format.fill
            fill.solid()
            fill.fore_color.rgb = colors[j % len(colors)]

    _textbox(sl, "Higher posting frequency = stronger content cadence, algorithmic favor, and better audience retention.",
             0.5, 6.0, 9.0, 0.35, font_size=11, color=C_LIGHT)


def slide_engagement(prs, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "ENGAGEMENT ANALYSIS & SCORE", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)
    
    _textbox(sl, "Engagement Rate is the truest indicator of content resonance. High views with low engagement suggests clickbait or poor retention.", 0.4, 1.0, 9.2, 0.4, font_size=11, color=C_LIGHT)

    companies = list(all_data.keys())
    for i, company in enumerate(companies):
        a = all_data[company].get("analytics", {})
        col = i % 2
        row = i // 2
        lx = 0.4 + col * 4.7
        ty = 1.6 + row * 1.9
        _rect(sl, lx, ty, 4.4, 1.7, C_CARD)
        _textbox(sl, company, lx + 0.15, ty + 0.1, 4.1, 0.35,
                 font_size=14, bold=True, color=C_PRIMARY)
                 
        intel_score = a.get('intelligence_score', 0)
        _textbox(sl, f"Intel Score: {intel_score}/100", lx + 2.5, ty + 0.1, 1.8, 0.35,
                 font_size=12, bold=True, color=C_ACCENT, align=PP_ALIGN.RIGHT)
                 
        metrics = [
            ("Avg Views", _fmt(a.get("avg_views", 0))),
            ("Avg Likes", _fmt(a.get("avg_likes", 0))),
            ("Eng. Rate", f"{a.get('avg_engagement_rate', 0)}%"),
        ]
        mx = lx + 0.1
        for label, val in metrics:
            _textbox(sl, val, mx, ty + 0.6, 1.3, 0.4,
                     font_size=16, bold=True, color=C_PRIMARY, align=PP_ALIGN.CENTER)
            _textbox(sl, label, mx, ty + 1.0, 1.3, 0.3,
                     font_size=10, color=C_LIGHT, align=PP_ALIGN.CENTER)
            mx += 1.4
        if ty > 5.5:
            break

def slide_gap_analysis(prs, own, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "STRATEGIC CONTENT GAPS", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)
    _textbox(sl, "Topics & formats competitors are actively covering that you are leaving on the table:",
             0.5, 1.0, 9.0, 0.4, font_size=12, color=C_LIGHT)

    all_themes: set = set()
    company_themes: dict = {}
    for company, data in all_data.items():
        themes = set(data.get("analytics", {}).get("content_themes", []))
        company_themes[company] = themes
        all_themes |= themes

    own_themes = company_themes.get(own, set())
    gaps = []
    for company, themes in company_themes.items():
        if company == own:
            continue
        missing = themes - own_themes
        if missing:
            gaps.append((company, list(missing)[:5]))

    top = 1.6
    if gaps:
        for comp, missing in gaps:
            _textbox(sl, f"► What {comp} covers, but {own} misses:",
                     0.5, top, 9.0, 0.32, font_size=13, bold=True, color=C_PRIMARY)
            top += 0.38
            _textbox(sl, "  " + "  |  ".join(missing),
                     0.6, top, 9.0, 0.28, font_size=11, color=C_ACCENT)
            top += 0.5
    else:
        _textbox(sl, "No significant content gaps found. You are covering the market well.",
                 0.5, top, 9.0, 0.4, font_size=12, color=C_PRIMARY)

def slide_recommendations(prs, own, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_PRIMARY)
    _textbox(sl, "VIDEO MARKETING STRATEGY & ACTION PLAN", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_WHITE)

    # Strategy insights based on data
    best = max(((c, d) for c, d in all_data.items() if c != own),
               key=lambda x: x[1].get("analytics", {}).get("avg_engagement_rate", 0), default=(None, {}))
    best_name = best[0] or "top competitor"
    
    own_freq = all_data.get(own, {}).get("analytics", {}).get("posting_frequency_per_month", 0)
    best_freq = best[1].get("analytics", {}).get("posting_frequency_per_month", 0)

    recs = [
        "1. Prioritize Viewer Retention Over Clickbait: High views with low engagement signals viewers are leaving early. Optimize the first 5 seconds.",
        f"2. Cadence Optimization: {best_name} posts {best_freq}x/month vs your {own_freq}x. Establish a consistent publishing schedule to train the algorithm.",
        "3. Capitalize on Content Gaps: Produce videos on the missing themes identified in Slide 8 to siphon audience from competitors.",
        "4. Vertical Video Expansion: Ensure you are publishing YouTube Shorts alongside long-form content to capture top-of-funnel discovery.",
        "5. Community Management: The algorithm rewards active channels. Reply to comments within the first 60 minutes of publishing.",
        "6. Conversion Funnel: Use end-screens and pinned comments to drive viewers off YouTube and onto your landing pages."
    ]
    top = 1.3
    for rec in recs:
        _rect(sl, 0.4, top, 9.2, 0.7, C_CARD)
        _textbox(sl, rec, 0.5, top + 0.1, 9.0, 0.5, font_size=12, color=C_PRIMARY)
        top += 0.85


def slide_scoring(prs, all_data):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 0, 10, 0.9, C_CARD)
    _textbox(sl, "INTELLIGENCE RANKINGS & SCORECARD", 0.4, 0.15, 9.2, 0.6,
             font_size=22, bold=True, color=C_PRIMARY)
    _textbox(sl, "Intelligence Score factors in Audience Size, Engagement Quality, and Consistency.",
             0.4, 1.0, 9.2, 0.4, font_size=11, color=C_LIGHT)

    scores = sorted(
        [(c, d.get("analytics", {}).get("intelligence_score", 0)) for c, d in all_data.items()],
        key=lambda x: x[1], reverse=True
    )

    headers = ["Rank", "Company", "Subscribers", "Posts/Mo", "Eng.Rate", "Intel Score"]
    col_x = [0.3, 0.9, 3.2, 5.1, 6.5, 7.9]
    col_w = [0.6, 2.3, 1.8, 1.3, 1.3, 1.5]
    top = 1.6
    for i, h in enumerate(headers):
        _textbox(sl, h, col_x[i], top, col_w[i], 0.35,
                 font_size=12, bold=True, color=C_PRIMARY)
    _divider(sl, 2.0, C_PRIMARY)

    top = 2.2
    medal = ["🥇", "🥈", "🥉"]
    for rank, (company, sc) in enumerate(scores, 1):
        data = all_data[company]
        a = data.get("analytics", {})
        ch = data.get("channel", {})
        _rect(sl, 0.3, top, 9.4, 0.45,
              C_CARD if rank % 2 == 0 else C_BG)
        row = [
            medal[rank-1] if rank <= 3 else str(rank),
            company[:22],
            _fmt(ch.get("subscribers", 0)),
            str(a.get("posting_frequency_per_month", 0)),
            f"{a.get('avg_engagement_rate', 0)}%",
            str(sc),
        ]
        for i, val in enumerate(row):
            color = C_ACCENT if rank == 1 else C_PRIMARY
            bold = rank == 1
            _textbox(sl, val, col_x[i], top + 0.08, col_w[i], 0.3,
                     font_size=11, bold=bold, color=color)
        top += 0.5


def slide_closing(prs, own, report_date):
    sl = _add_slide(prs)
    _fill_bg(sl, C_BG)
    _rect(sl, 0, 1.5, 10, 4.0, C_PRIMARY)
    _textbox(sl, "STRATEGY REPORT COMPLETE", 0.4, 2.0, 9.2, 0.8,
             font_size=34, bold=True, color=C_WHITE, align=PP_ALIGN.CENTER)
    _textbox(sl, f"Prepared exclusively for: {own}", 0.4, 2.9, 9.2, 0.5,
             font_size=16, color=C_ACCENT, align=PP_ALIGN.CENTER)
    _textbox(sl, f"Date: {report_date}", 0.4, 3.4, 9.2, 0.4,
             font_size=13, color=C_WHITE, align=PP_ALIGN.CENTER)
    _textbox(sl, "Powered by P2P — The Ultimate Video Intelligence Engine",
             0.4, 4.7, 9.2, 0.4, font_size=11, color=C_LIGHT, align=PP_ALIGN.CENTER)


# ══════════════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ══════════════════════════════════════════════════════════════════════════════

def generate_pptx(own_company: str, all_data: dict) -> bytes:
    """
    Build the full 11-slide PPTX and return raw bytes.
    all_data = { company_name: { "channel": {...}, "analytics": {...} }, ... }
    """
    prs = Presentation()
    prs.slide_width  = Inches(10)
    prs.slide_height = Inches(7.5)

    report_date = datetime.now().strftime("%d %B %Y")
    competitors = [c for c in all_data.keys() if c != own_company]

    slide_cover(prs, own_company, competitors, report_date)
    slide_executive_summary(prs, own_company, all_data)
    slide_channel_overview(prs, all_data)
    slide_subscribers_chart(prs, all_data)
    slide_top_videos(prs, all_data)
    slide_content_themes(prs, all_data)
    slide_posting_frequency(prs, all_data)
    slide_engagement(prs, all_data)
    slide_gap_analysis(prs, own_company, all_data)
    slide_recommendations(prs, own_company, all_data)
    slide_scoring(prs, all_data)
    slide_closing(prs, own_company, report_date)

    buf = io.BytesIO()
    prs.save(buf)
    return buf.getvalue()
