# Generated by Django 6.0.5 on 2026-05-19 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('own_company', models.CharField(max_length=200)),
                ('competitors_raw', models.TextField(help_text='JSON list of competitor names')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('channel_data_json', models.TextField(default='{}')),
                ('video_data_json', models.TextField(default='{}')),
                ('analysis_json', models.TextField(default='{}')),
                ('pptx_file', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
