# Generated by Django 6.0.5 on 2026-05-19 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_analysisreport_company_analysisreport_report_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysignup',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to='company_images/'),
        ),
        migrations.AddField(
            model_name='companysignup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
